field_skill_variants={
    # ===============================
    # Software / Computer Engineering
    # ===============================
    'javascript': ['js', 'java script'],
    'typescript': ['ts', 'type script'],
    'react': ['reactjs', 'react.js'],
    'angular': ['angularjs', 'angular.js'],
    'vue.js': ['vue', 'vuejs'],
    'next.js': ['nextjs', 'next'],
    'html5': ['html', 'hypertext markup language'],
    'css3': ['css', 'cascading style sheets'],
    'tailwind css': ['tailwindcss', 'tailwind'],
    'sass/scss': ['sass', 'scss'],
    'node.js': ['nodejs', 'node js', 'node'],
    'python': ['py', 'python3'],
    'django': ['django framework'],
    'flask': ['flask framework'],
    'java': ['jdk', 'jre'],
    'spring boot': ['springboot'],
    'c#': ['c sharp'],
    '.net core': ['dotnet core', 'dot net core'],
    'ruby on rails': ['ror'],
    'php': ['php7', 'php8'],
    'laravel': ['laravel framework'],
    'go': ['golang'],
    'rust': ['rustlang'],
    'sql': ['structured query language'],
    'postgresql': ['postgres', 'psql'],
    'mysql': ['my sql'],
    'mongodb': ['mongo db', 'mongo'],
    'redis': ['redis db'],
    'firebase': ['firebase db'],
    'dynamodb': ['amazon dynamodb'],
    'docker': ['docker container'],
    'kubernetes': ['k8s'],
    'aws': ['amazon web services'],
    'azure': ['microsoft azure'],
    'google cloud': ['gcp', 'google cloud platform'],
    'terraform': ['terraform iac'],
    'ci/cd': ['continuous integration', 'continuous delivery', 'continuous deployment'],
    'jenkins': ['jenkins ci'],
    'git': ['git vcs'],

    # AI / ML
    'machine learning': ['ml'],
    'tensorflow': ['tf'],
    'pytorch': ['torch'],
    'natural language processing': ['nlp'],
    'computer vision': ['cv'],
    'data science': ['ds'],

    # Emerging Tech
    'blockchain': ['dlt', 'distributed ledger technology'],
    'solidity': ['solidity language'],
    'web3': ['web 3'],
    'iot': ['internet of things'],
    'ar/vr': ['augmented reality', 'virtual reality'],

    # APIs
    'graphql': ['graph ql'],
    'rest apis': ['restful api', 'rest'],
    'grpc': ['google remote procedure call'],

    # Security
    'cybersecurity': ['cyber security'],
    'ethical hacking': ['penetration testing', 'pentest'],
    'penetration testing': ['pentesting'],

    # Processes
    'agile methodology': ['agile'],
    'scrum': ['scrum framework'],
    'jira': ['jira software'],
    'microservices architecture': ['microservices'],

    # ======================
    # Civil Engineering
    # ======================
    'autocad': ['auto cad', 'cad', 'computer aided design'],
    'revit': ['autodesk revit', 'bim'],
    'staad pro': ['staad', 'staad.pro'],
    'etabs': ['e-tabs', 'extended tabs'],
    'sap2000': ['sap 2000', 'structural analysis program'],
    'primavera p6': ['primavera', 'p6'],
    'ms project': ['microsoft project'],
    'bentley microstation': ['microstation'],
    'civil 3d': ['autocad civil 3d'],
    'sketchup': ['google sketchup'],
    'structural analysis': ['structure analysis'],
    'concrete design': ['reinforced concrete design'],
    'steel design': ['structural steel design'],
    'foundation design': ['footing design'],
    'highway design': ['road design'],
    'surveying': ['land surveying'],
    'construction management': ['construction mgmt'],
    'project management': ['pm', 'pmp'],
    'quantity surveying': ['qs'],
    'bill of quantities (boq)': ['boq', 'bill of quantity'],
    'site supervision': ['site engineer', 'site management'],
    'geotechnical engineering': ['soil mechanics'],
    'environmental engineering': ['env engineering'],
    'water resources engineering': ['hydraulic engineering'],
    'transportation engineering': ['traffic engineering'],

    # ======================
    # Mechanical Engineering
    # ======================
    'solidworks': ['solid works', 'sw'],
    'autocad mechanical': ['mechanical cad'],
    'catia': ['computer aided three dimensional interactive application'],
    'creo (pro/engineer)': ['creo', 'pro engineer', 'pro/engineer'],
    'inventor': ['autodesk inventor'],
    'fusion 360': ['fusion360'],
    'ansys': ['finite element analysis', 'fea'],
    'matlab': ['matrix laboratory'],
    'simulink': ['matlab simulink'],
    'abaqus': ['abaqus cae'],
    'nx (unigraphics)': ['siemens nx', 'unigraphics'],
    'finite element analysis (fea)': ['fea'],
    'computational fluid dynamics (cfd)': ['cfd'],
    'thermodynamics': ['thermo'],
    'heat transfer': ['thermal transfer'],
    'fluid mechanics': ['fluids'],
    'machine design': ['mechanical design'],
    'manufacturing processes': ['production processes'],
    'cnc programming': ['cnc machining'],
    'lean manufacturing': ['lean'],
    'six sigma': ['6 sigma', 'lean six sigma'],
    'quality control': ['qc', 'quality assurance', 'qa'],
    'material science': ['materials science'],
    'robotics': ['automation robotics'],
    'hvac design': ['heating ventilation and air conditioning'],
    'automotive engineering': ['auto engineering'],
    'product design': ['industrial design'],

    # ======================
    # Electrical Engineering
    # ======================
    'matlab/simulink': ['matlab simulink'],
    'labview': ['lab view'],
    'pspice': ['p-spice', 'spice'],
    'multisim': ['multi-sim'],
    'altium designer': ['altium'],
    'eagle pcb': ['eagle'],
    'kicad': ['ki cad'],
    'etap': ['electrical transient analyzer program'],
    'powerworld': ['power world'],
    'autocad electrical': ['electrical cad'],
    'eplan': ['eplan electric'],
    'plc programming': ['plc', 'programmable logic controller'],
    'scada systems': ['scada'],
    'hmi design': ['human machine interface'],
    'power systems analysis': ['psa'],
    'circuit analysis': ['circuits'],
    'digital signal processing': ['dsp'],
    'control systems': ['controls'],
    'embedded systems': ['embedded dev'],
    'microcontrollers': ['mcu'],
    'arduino': ['arduino board'],
    'raspberry pi': ['raspi'],
    'fpga programming': ['fpga'],
    'vhdl': ['vhsic hardware description language'],
    'verilog': ['verilog hdl'],
    'power electronics': ['pe'],
    'motor control': ['motor drives'],
    'renewable energy systems': ['res'],
    'smart grid': ['intelligent grid'],
    'telecommunications': ['telecom'],
    'rf engineering': ['radio frequency engineering'],

    # ======================
    # Chemical Engineering
    # ======================
    'aspen plus': ['aspenplus'],
    'aspen hysys': ['hysys'],
    'chemcad': ['chem cad'],
    'ansys fluent': ['fluent'],
    'comsol multiphysics': ['comsol'],
    'process design': ['chemical process design'],
    'process simulation': ['chemical process simulation'],
    'distillation design': ['distillation column design'],
    'reactor design': ['chemical reactor design'],
    'heat exchanger design': ['heat exchanger'],
    'mass transfer': ['mass transport'],
    'chemical kinetics': ['reaction kinetics'],
    'process control': ['chemical process control'],
    'process safety': ['psm'],
    'hazop studies': ['hazard and operability study'],
    'petrochemical processes': ['petchem'],
    'pharmaceutical manufacturing': ['pharma manufacturing'],
    'biochemical engineering': ['bioengineering'],
    'materials engineering': ['materials science'],

    # ======================
    # Industrial Engineering
    # ======================
    'operations research': ['or'],
    'supply chain management': ['scm'],
    'statistical process control': ['spc'],
    'quality management': ['qm'],
    'production planning': ['pp'],
    'inventory management': ['im'],
    'facility layout design': ['facility planning'],
    'work study': ['time study'],
    'time and motion study': ['tms'],
    'ergonomics': ['human factors'],
    'cost engineering': ['cost estimation'],
    'enterprise resource planning (erp)': ['erp'],
    'material requirements planning (mrp)': ['mrp'],
    'just-in-time (jit)': ['jit'],
    'total quality management (tqm)': ['tqm'],
    'simulation modeling': ['sim modeling'],
    'business process improvement': ['bpi'],

    # ======================
    # General & Professional Skills
    # ======================
    'technical writing': ['tech writing'],
    'safety engineering': ['safety eng'],
    'leadership': ['team leadership'],
    'team management': ['team leadership'],
    'communication skills': ['communications'],
    'presentation skills': ['public speaking'],
    'negotiation': ['negotiating'],
    'time management': ['timely delivery'],
    'strategic planning': ['strategic mgmt'],
    'budget management': ['budgeting'],
    'stakeholder management': ['stakeholder relations'],
    'vendor management': ['supplier management'],
    'contract management': ['contracts'],
    'business development': ['bizdev'],
    'customer relations': ['customer service'],
    'cross-functional collaboration': ['cross team collaboration'],
    'change management': ['change control'],
    'mentoring': ['coaching'],
    'training & development': ['training'],
    'performance management': ['performance review'],
    'regulatory compliance': ['compliance'],
    'international standards (iso)': ['iso certification']
}

