export const skillsData=[
    {"id": 1, "name": "JavaScript", "category": "Frontend"},
    {"id": 2, "name": "TypeScript", "category": "Frontend"},
    {"id": 3, "name": "React", "category": "Frontend"},
    {"id": 4, "name": "Angular", "category": "Frontend"},
    {"id": 5, "name": "Vue.js", "category": "Frontend"},
    {"id": 6, "name": "Next.js", "category": "Frontend"},
    {"id": 7, "name": "HTML5", "category": "Frontend"},
    {"id": 8, "name": "CSS3", "category": "Frontend"},
    {"id": 9, "name": "Tailwind CSS", "category": "Frontend"},
    {"id": 10, "name": "SASS/SCSS", "category": "Frontend"},
    
    {"id": 11, "name": "Node.js", "category": "Backend"},
    {"id": 12, "name": "Python", "category": "Backend"},
    {"id": 13, "name": "Django", "category": "Backend"},
    {"id": 14, "name": "Flask", "category": "Backend"},
    {"id": 15, "name": "Java", "category": "Backend"},
    {"id": 16, "name": "Spring Boot", "category": "Backend"},
    {"id": 17, "name": "C#", "category": "Backend"},
    {"id": 18, "name": ".NET Core", "category": "Backend"},
    {"id": 19, "name": "Ruby on Rails", "category": "Backend"},
    {"id": 20, "name": "PHP", "category": "Backend"},
    {"id": 21, "name": "Laravel", "category": "Backend"},
    {"id": 22, "name": "Go", "category": "Backend"},
    {"id": 23, "name": "Rust", "category": "Backend"},
    
    {"id": 24, "name": "SQL", "category": "Database"},
    {"id": 25, "name": "PostgreSQL", "category": "Database"},
    {"id": 26, "name": "MySQL", "category": "Database"},
    {"id": 27, "name": "MongoDB", "category": "Database"},
    {"id": 28, "name": "Redis", "category": "Database"},
    {"id": 29, "name": "Firebase", "category": "Database"},
    {"id": 30, "name": "DynamoDB", "category": "Database"},
    
    {"id": 31, "name": "Docker", "category": "DevOps"},
    {"id": 32, "name": "Kubernetes", "category": "DevOps"},
    {"id": 33, "name": "AWS", "category": "DevOps"},
    {"id": 34, "name": "Azure", "category": "DevOps"},
    {"id": 35, "name": "Google Cloud", "category": "DevOps"},
    {"id": 36, "name": "Terraform", "category": "DevOps"},
    {"id": 37, "name": "CI/CD", "category": "DevOps"},
    {"id": 38, "name": "Jenkins", "category": "DevOps"},
    {"id": 39, "name": "Git", "category": "DevOps"},
    
    {"id": 40, "name": "Machine Learning", "category": "AI/ML"},
    {"id": 41, "name": "TensorFlow", "category": "AI/ML"},
    {"id": 42, "name": "PyTorch", "category": "AI/ML"},
    {"id": 43, "name": "Natural Language Processing", "category": "AI/ML"},
    {"id": 44, "name": "Computer Vision", "category": "AI/ML"},
    {"id": 45, "name": "Data Science", "category": "AI/ML"},
    
    {"id": 46, "name": "Blockchain", "category": "Emerging Tech"},
    {"id": 47, "name": "Solidity", "category": "Emerging Tech"},
    {"id": 48, "name": "Web3", "category": "Emerging Tech"},
    {"id": 49, "name": "IoT", "category": "Emerging Tech"},
    {"id": 50, "name": "AR/VR", "category": "Emerging Tech"},
    
    {"id": 51, "name": "GraphQL", "category": "APIs"},
    {"id": 52, "name": "REST APIs", "category": "APIs"},
    {"id": 53, "name": "gRPC", "category": "APIs"},
    
    {"id": 54, "name": "Cybersecurity", "category": "Security"},
    {"id": 55, "name": "Ethical Hacking", "category": "Security"},
    {"id": 56, "name": "Penetration Testing", "category": "Security"},
    
    {"id": 57, "name": "Agile Methodology", "category": "Process"},
    {"id": 58, "name": "Scrum", "category": "Process"},
    {"id": 59, "name": "JIRA", "category": "Process"},
    {"id": 60, "name": "Microservices Architecture", "category": "Architecture"}
  ]