export const skillsData = [
  // Software Engineering / Computer Science
  {"id": 1, "name": "JavaScript", "category": "Frontend"},
  {"id": 2, "name": "TypeScript", "category": "Frontend"},
  {"id": 3, "name": "React", "category": "Frontend"},
  {"id": 4, "name": "Angular", "category": "Frontend"},
  {"id": 5, "name": "Vue.js", "category": "Frontend"},
  {"id": 6, "name": "Next.js", "category": "Frontend"},
  {"id": 7, "name": "HTML5", "category": "Frontend"},
  {"id": 8, "name": "CSS3", "category": "Frontend"},
  {"id": 9, "name": "Tailwind CSS", "category": "Frontend"},
  {"id": 10, "name": "SASS/SCSS", "category": "Frontend"},
  
  {"id": 11, "name": "Node.js", "category": "Backend"},
  {"id": 12, "name": "Python", "category": "Backend"},
  {"id": 13, "name": "Django", "category": "Backend"},
  {"id": 14, "name": "Flask", "category": "Backend"},
  {"id": 15, "name": "Java", "category": "Backend"},
  {"id": 16, "name": "Spring Boot", "category": "Backend"},
  {"id": 17, "name": "C#", "category": "Backend"},
  {"id": 18, "name": ".NET Core", "category": "Backend"},
  {"id": 19, "name": "Ruby on Rails", "category": "Backend"},
  {"id": 20, "name": "PHP", "category": "Backend"},
  {"id": 21, "name": "Laravel", "category": "Backend"},
  {"id": 22, "name": "Go", "category": "Backend"},
  {"id": 23, "name": "Rust", "category": "Backend"},
  
  {"id": 24, "name": "SQL", "category": "Database"},
  {"id": 25, "name": "PostgreSQL", "category": "Database"},
  {"id": 26, "name": "MySQL", "category": "Database"},
  {"id": 27, "name": "MongoDB", "category": "Database"},
  {"id": 28, "name": "Redis", "category": "Database"},
  {"id": 29, "name": "Firebase", "category": "Database"},
  {"id": 30, "name": "DynamoDB", "category": "Database"},
  
  {"id": 31, "name": "Docker", "category": "DevOps"},
  {"id": 32, "name": "Kubernetes", "category": "DevOps"},
  {"id": 33, "name": "AWS", "category": "DevOps"},
  {"id": 34, "name": "Azure", "category": "DevOps"},
  {"id": 35, "name": "Google Cloud", "category": "DevOps"},
  {"id": 36, "name": "Terraform", "category": "DevOps"},
  {"id": 37, "name": "CI/CD", "category": "DevOps"},
  {"id": 38, "name": "Jenkins", "category": "DevOps"},
  {"id": 39, "name": "Git", "category": "DevOps"},
  
  {"id": 40, "name": "Machine Learning", "category": "AI/ML"},
  {"id": 41, "name": "TensorFlow", "category": "AI/ML"},
  {"id": 42, "name": "PyTorch", "category": "AI/ML"},
  {"id": 43, "name": "Natural Language Processing", "category": "AI/ML"},
  {"id": 44, "name": "Computer Vision", "category": "AI/ML"},
  {"id": 45, "name": "Data Science", "category": "AI/ML"},
  
  {"id": 46, "name": "Blockchain", "category": "Emerging Tech"},
  {"id": 47, "name": "Solidity", "category": "Emerging Tech"},
  {"id": 48, "name": "Web3", "category": "Emerging Tech"},
  {"id": 49, "name": "IoT", "category": "Emerging Tech"},
  {"id": 50, "name": "AR/VR", "category": "Emerging Tech"},
  
  {"id": 51, "name": "GraphQL", "category": "APIs"},
  {"id": 52, "name": "REST APIs", "category": "APIs"},
  {"id": 53, "name": "gRPC", "category": "APIs"},
  
  {"id": 54, "name": "Cybersecurity", "category": "Security"},
  {"id": 55, "name": "Ethical Hacking", "category": "Security"},
  {"id": 56, "name": "Penetration Testing", "category": "Security"},
  
  {"id": 57, "name": "Agile Methodology", "category": "Process"},
  {"id": 58, "name": "Scrum", "category": "Process"},
  {"id": 59, "name": "JIRA", "category": "Process"},
  {"id": 60, "name": "Microservices Architecture", "category": "Architecture"},

  // Civil Engineering
  {"id": 61, "name": "AutoCAD", "category": "Civil Engineering"},
  {"id": 62, "name": "Revit", "category": "Civil Engineering"},
  {"id": 63, "name": "STAAD Pro", "category": "Civil Engineering"},
  {"id": 64, "name": "ETABS", "category": "Civil Engineering"},
  {"id": 65, "name": "SAP2000", "category": "Civil Engineering"},
  {"id": 66, "name": "Primavera P6", "category": "Civil Engineering"},
  {"id": 67, "name": "MS Project", "category": "Civil Engineering"},
  {"id": 68, "name": "Bentley MicroStation", "category": "Civil Engineering"},
  {"id": 69, "name": "Civil 3D", "category": "Civil Engineering"},
  {"id": 70, "name": "SketchUp", "category": "Civil Engineering"},
  {"id": 71, "name": "Structural Analysis", "category": "Civil Engineering"},
  {"id": 72, "name": "Concrete Design", "category": "Civil Engineering"},
  {"id": 73, "name": "Steel Design", "category": "Civil Engineering"},
  {"id": 74, "name": "Foundation Design", "category": "Civil Engineering"},
  {"id": 75, "name": "Highway Design", "category": "Civil Engineering"},
  {"id": 76, "name": "Surveying", "category": "Civil Engineering"},
  {"id": 77, "name": "Construction Management", "category": "Civil Engineering"},
  {"id": 78, "name": "Project Management", "category": "Civil Engineering"},
  {"id": 79, "name": "Quantity Surveying", "category": "Civil Engineering"},
  {"id": 80, "name": "Bill of Quantities (BOQ)", "category": "Civil Engineering"},
  {"id": 81, "name": "Site Supervision", "category": "Civil Engineering"},
  {"id": 82, "name": "Geotechnical Engineering", "category": "Civil Engineering"},
  {"id": 83, "name": "Environmental Engineering", "category": "Civil Engineering"},
  {"id": 84, "name": "Water Resources Engineering", "category": "Civil Engineering"},
  {"id": 85, "name": "Transportation Engineering", "category": "Civil Engineering"},

  // Mechanical Engineering
  {"id": 86, "name": "SolidWorks", "category": "Mechanical Engineering"},
  {"id": 87, "name": "AutoCAD Mechanical", "category": "Mechanical Engineering"},
  {"id": 88, "name": "CATIA", "category": "Mechanical Engineering"},
  {"id": 89, "name": "Creo (Pro/Engineer)", "category": "Mechanical Engineering"},
  {"id": 90, "name": "Inventor", "category": "Mechanical Engineering"},
  {"id": 91, "name": "Fusion 360", "category": "Mechanical Engineering"},
  {"id": 92, "name": "ANSYS", "category": "Mechanical Engineering"},
  {"id": 93, "name": "MATLAB", "category": "Mechanical Engineering"},
  {"id": 94, "name": "Simulink", "category": "Mechanical Engineering"},
  {"id": 95, "name": "ABAQUS", "category": "Mechanical Engineering"},
  {"id": 96, "name": "NX (Unigraphics)", "category": "Mechanical Engineering"},
  {"id": 97, "name": "Finite Element Analysis (FEA)", "category": "Mechanical Engineering"},
  {"id": 98, "name": "Computational Fluid Dynamics (CFD)", "category": "Mechanical Engineering"},
  {"id": 99, "name": "Thermodynamics", "category": "Mechanical Engineering"},
  {"id": 100, "name": "Heat Transfer", "category": "Mechanical Engineering"},
  {"id": 101, "name": "Fluid Mechanics", "category": "Mechanical Engineering"},
  {"id": 102, "name": "Machine Design", "category": "Mechanical Engineering"},
  {"id": 103, "name": "Manufacturing Processes", "category": "Mechanical Engineering"},
  {"id": 104, "name": "CNC Programming", "category": "Mechanical Engineering"},
  {"id": 105, "name": "Lean Manufacturing", "category": "Mechanical Engineering"},
  {"id": 106, "name": "Six Sigma", "category": "Mechanical Engineering"},
  {"id": 107, "name": "Quality Control", "category": "Mechanical Engineering"},
  {"id": 108, "name": "Material Science", "category": "Mechanical Engineering"},
  {"id": 109, "name": "Robotics", "category": "Mechanical Engineering"},
  {"id": 110, "name": "HVAC Design", "category": "Mechanical Engineering"},
  {"id": 111, "name": "Automotive Engineering", "category": "Mechanical Engineering"},
  {"id": 112, "name": "Product Design", "category": "Mechanical Engineering"},

  // Electrical Engineering
  {"id": 113, "name": "MATLAB/Simulink", "category": "Electrical Engineering"},
  {"id": 114, "name": "LabVIEW", "category": "Electrical Engineering"},
  {"id": 115, "name": "PSpice", "category": "Electrical Engineering"},
  {"id": 116, "name": "Multisim", "category": "Electrical Engineering"},
  {"id": 117, "name": "Altium Designer", "category": "Electrical Engineering"},
  {"id": 118, "name": "Eagle PCB", "category": "Electrical Engineering"},
  {"id": 119, "name": "KiCad", "category": "Electrical Engineering"},
  {"id": 120, "name": "ETAP", "category": "Electrical Engineering"},
  {"id": 121, "name": "PowerWorld", "category": "Electrical Engineering"},
  {"id": 122, "name": "AutoCAD Electrical", "category": "Electrical Engineering"},
  {"id": 123, "name": "EPLAN", "category": "Electrical Engineering"},
  {"id": 124, "name": "PLC Programming", "category": "Electrical Engineering"},
  {"id": 125, "name": "SCADA Systems", "category": "Electrical Engineering"},
  {"id": 126, "name": "HMI Design", "category": "Electrical Engineering"},
  {"id": 127, "name": "Power Systems Analysis", "category": "Electrical Engineering"},
  {"id": 128, "name": "Circuit Analysis", "category": "Electrical Engineering"},
  {"id": 129, "name": "Digital Signal Processing", "category": "Electrical Engineering"},
  {"id": 130, "name": "Control Systems", "category": "Electrical Engineering"},
  {"id": 131, "name": "Embedded Systems", "category": "Electrical Engineering"},
  {"id": 132, "name": "Microcontrollers", "category": "Electrical Engineering"},
  {"id": 133, "name": "Arduino", "category": "Electrical Engineering"},
  {"id": 134, "name": "Raspberry Pi", "category": "Electrical Engineering"},
  {"id": 135, "name": "FPGA Programming", "category": "Electrical Engineering"},
  {"id": 136, "name": "VHDL", "category": "Electrical Engineering"},
  {"id": 137, "name": "Verilog", "category": "Electrical Engineering"},
  {"id": 138, "name": "Power Electronics", "category": "Electrical Engineering"},
  {"id": 139, "name": "Motor Control", "category": "Electrical Engineering"},
  {"id": 140, "name": "Renewable Energy Systems", "category": "Electrical Engineering"},
  {"id": 141, "name": "Smart Grid", "category": "Electrical Engineering"},
  {"id": 142, "name": "Telecommunications", "category": "Electrical Engineering"},
  {"id": 143, "name": "RF Engineering", "category": "Electrical Engineering"},

  // Chemical Engineering
  {"id": 144, "name": "Aspen Plus", "category": "Chemical Engineering"},
  {"id": 145, "name": "Aspen HYSYS", "category": "Chemical Engineering"},
  {"id": 146, "name": "ChemCAD", "category": "Chemical Engineering"},
  {"id": 147, "name": "MATLAB", "category": "Chemical Engineering"},
  {"id": 148, "name": "Simulink", "category": "Chemical Engineering"},
  {"id": 149, "name": "ANSYS Fluent", "category": "Chemical Engineering"},
  {"id": 150, "name": "COMSOL Multiphysics", "category": "Chemical Engineering"},
  {"id": 151, "name": "Process Design", "category": "Chemical Engineering"},
  {"id": 152, "name": "Process Simulation", "category": "Chemical Engineering"},
  {"id": 153, "name": "Distillation Design", "category": "Chemical Engineering"},
  {"id": 154, "name": "Reactor Design", "category": "Chemical Engineering"},
  {"id": 155, "name": "Heat Exchanger Design", "category": "Chemical Engineering"},
  {"id": 156, "name": "Mass Transfer", "category": "Chemical Engineering"},
  {"id": 157, "name": "Heat Transfer", "category": "Chemical Engineering"},
  {"id": 158, "name": "Fluid Mechanics", "category": "Chemical Engineering"},
  {"id": 159, "name": "Thermodynamics", "category": "Chemical Engineering"},
  {"id": 160, "name": "Chemical Kinetics", "category": "Chemical Engineering"},
  {"id": 161, "name": "Process Control", "category": "Chemical Engineering"},
  {"id": 162, "name": "Process Safety", "category": "Chemical Engineering"},
  {"id": 163, "name": "HAZOP Studies", "category": "Chemical Engineering"},
  {"id": 164, "name": "Petrochemical Processes", "category": "Chemical Engineering"},
  {"id": 165, "name": "Pharmaceutical Manufacturing", "category": "Chemical Engineering"},
  {"id": 166, "name": "Biochemical Engineering", "category": "Chemical Engineering"},
  {"id": 167, "name": "Environmental Engineering", "category": "Chemical Engineering"},
  {"id": 168, "name": "Materials Engineering", "category": "Chemical Engineering"},

  // Industrial Engineering
  {"id": 169, "name": "Operations Research", "category": "Industrial Engineering"},
  {"id": 170, "name": "Supply Chain Management", "category": "Industrial Engineering"},
  {"id": 171, "name": "Lean Manufacturing", "category": "Industrial Engineering"},
  {"id": 172, "name": "Six Sigma", "category": "Industrial Engineering"},
  {"id": 173, "name": "Statistical Process Control", "category": "Industrial Engineering"},
  {"id": 174, "name": "Quality Management", "category": "Industrial Engineering"},
  {"id": 175, "name": "Production Planning", "category": "Industrial Engineering"},
  {"id": 176, "name": "Inventory Management", "category": "Industrial Engineering"},
  {"id": 177, "name": "Facility Layout Design", "category": "Industrial Engineering"},
  {"id": 178, "name": "Work Study", "category": "Industrial Engineering"},
  {"id": 179, "name": "Time and Motion Study", "category": "Industrial Engineering"},
  {"id": 180, "name": "Ergonomics", "category": "Industrial Engineering"},
  {"id": 181, "name": "Project Management", "category": "Industrial Engineering"},
  {"id": 182, "name": "Cost Engineering", "category": "Industrial Engineering"},
  {"id": 183, "name": "Enterprise Resource Planning (ERP)", "category": "Industrial Engineering"},
  {"id": 184, "name": "Material Requirements Planning (MRP)", "category": "Industrial Engineering"},
  {"id": 185, "name": "Just-in-Time (JIT)", "category": "Industrial Engineering"},
  {"id": 186, "name": "Total Quality Management (TQM)", "category": "Industrial Engineering"},
  {"id": 187, "name": "Simulation Modeling", "category": "Industrial Engineering"},
  {"id": 188, "name": "Data Analytics", "category": "Industrial Engineering"},
  {"id": 189, "name": "Business Process Improvement", "category": "Industrial Engineering"},

  // Aerospace Engineering
  {"id": 190, "name": "CATIA", "category": "Aerospace Engineering"},
  {"id": 191, "name": "SolidWorks", "category": "Aerospace Engineering"},
  {"id": 192, "name": "ANSYS", "category": "Aerospace Engineering"},
  {"id": 193, "name": "MATLAB", "category": "Aerospace Engineering"},
  {"id": 194, "name": "Simulink", "category": "Aerospace Engineering"},
  {"id": 195, "name": "CFD Analysis", "category": "Aerospace Engineering"},
  {"id": 196, "name": "Aerodynamics", "category": "Aerospace Engineering"},
  {"id": 197, "name": "Flight Dynamics", "category": "Aerospace Engineering"},
  {"id": 198, "name": "Aircraft Design", "category": "Aerospace Engineering"},
  {"id": 199, "name": "Propulsion Systems", "category": "Aerospace Engineering"},
  {"id": 200, "name": "Avionics", "category": "Aerospace Engineering"},
  {"id": 201, "name": "Flight Control Systems", "category": "Aerospace Engineering"},
  {"id": 202, "name": "Satellite Systems", "category": "Aerospace Engineering"},
  {"id": 203, "name": "Mission Design", "category": "Aerospace Engineering"},
  {"id": 204, "name": "Structural Analysis", "category": "Aerospace Engineering"},
  {"id": 205, "name": "Materials Science", "category": "Aerospace Engineering"},
  {"id": 206, "name": "Systems Engineering", "category": "Aerospace Engineering"},
  {"id": 207, "name": "Flight Testing", "category": "Aerospace Engineering"},

  // Biomedical Engineering
  {"id": 208, "name": "MATLAB", "category": "Biomedical Engineering"},
  {"id": 209, "name": "LabVIEW", "category": "Biomedical Engineering"},
  {"id": 210, "name": "SolidWorks", "category": "Biomedical Engineering"},
  {"id": 211, "name": "ANSYS", "category": "Biomedical Engineering"},
  {"id": 212, "name": "Medical Device Design", "category": "Biomedical Engineering"},
  {"id": 213, "name": "Biomechanics", "category": "Biomedical Engineering"},
  {"id": 214, "name": "Biomaterials", "category": "Biomedical Engineering"},
  {"id": 215, "name": "Biomedical Instrumentation", "category": "Biomedical Engineering"},
  {"id": 216, "name": "Signal Processing", "category": "Biomedical Engineering"},
  {"id": 217, "name": "Medical Imaging", "category": "Biomedical Engineering"},
  {"id": 218, "name": "Tissue Engineering", "category": "Biomedical Engineering"},
  {"id": 219, "name": "Regulatory Affairs", "category": "Biomedical Engineering"},
  {"id": 220, "name": "FDA Compliance", "category": "Biomedical Engineering"},
  {"id": 221, "name": "Clinical Research", "category": "Biomedical Engineering"},
  {"id": 222, "name": "Bioinformatics", "category": "Biomedical Engineering"},
  {"id": 223, "name": "Prosthetics Design", "category": "Biomedical Engineering"},

  // Environmental Engineering
  {"id": 224, "name": "Water Treatment Design", "category": "Environmental Engineering"},
  {"id": 225, "name": "Wastewater Treatment", "category": "Environmental Engineering"},
  {"id": 226, "name": "Air Pollution Control", "category": "Environmental Engineering"},
  {"id": 227, "name": "Environmental Impact Assessment", "category": "Environmental Engineering"},
  {"id": 228, "name": "Soil Remediation", "category": "Environmental Engineering"},
  {"id": 229, "name": "Waste Management", "category": "Environmental Engineering"},
  {"id": 230, "name": "Environmental Modeling", "category": "Environmental Engineering"},
  {"id": 231, "name": "GIS (Geographic Information Systems)", "category": "Environmental Engineering"},
  {"id": 232, "name": "Remote Sensing", "category": "Environmental Engineering"},
  {"id": 233, "name": "Environmental Chemistry", "category": "Environmental Engineering"},
  {"id": 234, "name": "Hydrology", "category": "Environmental Engineering"},
  {"id": 235, "name": "Groundwater Modeling", "category": "Environmental Engineering"},
  {"id": 236, "name": "Environmental Regulations", "category": "Environmental Engineering"},
  {"id": 237, "name": "Sustainability Assessment", "category": "Environmental Engineering"},
  {"id": 238, "name": "Life Cycle Assessment", "category": "Environmental Engineering"},

  // Petroleum Engineering
  {"id": 239, "name": "Reservoir Simulation", "category": "Petroleum Engineering"},
  {"id": 240, "name": "Drilling Engineering", "category": "Petroleum Engineering"},
  {"id": 241, "name": "Production Engineering", "category": "Petroleum Engineering"},
  {"id": 242, "name": "Petrophysics", "category": "Petroleum Engineering"},
  {"id": 243, "name": "Well Completion", "category": "Petroleum Engineering"},
  {"id": 244, "name": "Enhanced Oil Recovery", "category": "Petroleum Engineering"},
  {"id": 245, "name": "Reservoir Engineering", "category": "Petroleum Engineering"},
  {"id": 246, "name": "Petroleum Economics", "category": "Petroleum Engineering"},
  {"id": 247, "name": "Seismic Interpretation", "category": "Petroleum Engineering"},
  {"id": 248, "name": "Well Testing", "category": "Petroleum Engineering"},
  {"id": 249, "name": "Formation Evaluation", "category": "Petroleum Engineering"},
  {"id": 250, "name": "Pipeline Engineering", "category": "Petroleum Engineering"},

  // Mining Engineering
  {"id": 251, "name": "Mine Planning", "category": "Mining Engineering"},
  {"id": 252, "name": "Ore Reserve Estimation", "category": "Mining Engineering"},
  {"id": 253, "name": "Mine Ventilation", "category": "Mining Engineering"},
  {"id": 254, "name": "Rock Mechanics", "category": "Mining Engineering"},
  {"id": 255, "name": "Mineral Processing", "category": "Mining Engineering"},
  {"id": 256, "name": "Metallurgy", "category": "Mining Engineering"},
  {"id": 257, "name": "Mine Safety", "category": "Mining Engineering"},
  {"id": 258, "name": "Explosives Engineering", "category": "Mining Engineering"},
  {"id": 259, "name": "Surveying", "category": "Mining Engineering"},
  {"id": 260, "name": "Geotechnical Engineering", "category": "Mining Engineering"},

  // General Engineering Skills
  {"id": 261, "name": "Engineering Mathematics", "category": "General Engineering"},
  {"id": 262, "name": "Statistics", "category": "General Engineering"},
  {"id": 263, "name": "Technical Writing", "category": "General Engineering"},
  {"id": 264, "name": "Research Methodology", "category": "General Engineering"},
  {"id": 265, "name": "Patent Writing", "category": "General Engineering"},
  {"id": 266, "name": "Engineering Economics", "category": "General Engineering"},
  {"id": 267, "name": "Risk Assessment", "category": "General Engineering"},
  {"id": 268, "name": "Safety Engineering", "category": "General Engineering"},
  {"id": 269, "name": "Failure Analysis", "category": "General Engineering"},
  {"id": 270, "name": "Reverse Engineering", "category": "General Engineering"},
  {"id": 271, "name": "Value Engineering", "category": "General Engineering"},
  {"id": 272, "name": "Design for Manufacturing", "category": "General Engineering"},
  {"id": 273, "name": "Design for Assembly", "category": "General Engineering"},
  {"id": 274, "name": "Finite Element Method", "category": "General Engineering"},
  {"id": 275, "name": "Optimization Techniques", "category": "General Engineering"},
  {"id": 276, "name": "Systems Thinking", "category": "General Engineering"},
  {"id": 277, "name": "Problem Solving", "category": "General Engineering"},
  {"id": 278, "name": "Critical Thinking", "category": "General Engineering"},
  {"id": 279, "name": "Innovation Management", "category": "General Engineering"},
  {"id": 280, "name": "Technology Transfer", "category": "General Engineering"},

  // Professional Skills (Universal)
  {"id": 281, "name": "Leadership", "category": "Professional Skills"},
  {"id": 282, "name": "Team Management", "category": "Professional Skills"},
  {"id": 283, "name": "Communication Skills", "category": "Professional Skills"},
  {"id": 284, "name": "Presentation Skills", "category": "Professional Skills"},
  {"id": 285, "name": "Negotiation", "category": "Professional Skills"},
  {"id": 286, "name": "Time Management", "category": "Professional Skills"},
  {"id": 287, "name": "Strategic Planning", "category": "Professional Skills"},
  {"id": 288, "name": "Budget Management", "category": "Professional Skills"},
  {"id": 289, "name": "Stakeholder Management", "category": "Professional Skills"},
  {"id": 290, "name": "Vendor Management", "category": "Professional Skills"},
  {"id": 291, "name": "Contract Management", "category": "Professional Skills"},
  {"id": 292, "name": "Business Development", "category": "Professional Skills"},
  {"id": 293, "name": "Customer Relations", "category": "Professional Skills"},
  {"id": 294, "name": "Cross-functional Collaboration", "category": "Professional Skills"},
  {"id": 295, "name": "Change Management", "category": "Professional Skills"},
  {"id": 296, "name": "Mentoring", "category": "Professional Skills"},
  {"id": 297, "name": "Training & Development", "category": "Professional Skills"},
  {"id": 298, "name": "Performance Management", "category": "Professional Skills"},
  {"id": 299, "name": "Regulatory Compliance", "category": "Professional Skills"},
  {"id": 300, "name": "International Standards (ISO)", "category": "Professional Skills"}
];